language: java

sudo: false

cache:
  apt: true
  directories:
    - ~/.m2

branches:
  only:
    - master

install:
  -
  
matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env:
        - DESC="clean compile"
        - CMD="mvn clean compile -DskipTests=true"
        - COVERAGE_CMD=""
        - DEPLOY="false"

